### PR TITLE
Successfully delete gitopsconfig if deployment unsuccessful

### LINKED ISSUE #52: Operator doesn't handle errors well
## What happens?
During the testing of the new examples, a couple of problems were observed:
- The operator sometimes gets stuck and doesn't start new jobs if the previous didn't complete successfully. A restart is required.
- When there are errors with the repo (no access, wrong branch, missing files, missing template image) and the config doesn't get applied, the GitOpsConfig CRs often can't be deleted afterwards. The Finalizer has to be disabled to remove it.
- Behavior affects other namespaces also.

Not sure if these are related. I'll keep documenting more behaviors as I do more testing.

## What were you expecting to happen?
The Operator gracefully handles any issues, doesn't get "stuck" , and the CR can always be deleted without having to "patch" the resource.

## Steps to reproduce: 
- Use the examples and modify one of the CRs to not being able to pull the repo. Leave the trigger as `change`.
- Apply the CR and let it spin.
- Try deleting the CR
- Try applying an other CR in a different namespace

### PR DESCRIPTION
**Pull request by sbar95**
**Description**

Change the way gitopsconfig resources are being deleted in
resourceManager.sh - now everything having a proper label will be
deleted. Deletion job is not failing due to invalid URL, templates or
parameters dir, or wrong branch anymore.

- **Important:** This PR doesn't fix the case where there is a wrong (unreachable or nonexistent) templateProcessorImage in CR defined (created #216 to track it separately).

Fixes #52

**Type of change**

* Bug fix (non-breaking change which fixes an issue)

**Checklist**

- [ ] Unit tests and e2e tests updated
- [ ] Documentation updated

### CODE REVIEW

File: pkg/controller/gitopsconfig/controller.go [hunk 1]
```diff
@@ -414,24 +414,23 @@ func (r *Reconciler) manageDeletion(instance *gitopsv1alpha1.GitOpsConfig) (reco
 		//we return because we need to wait for the job to stop
 		return reconcile.Result{
 			Requeue:      true,
-			RequeueAfter: time.Minute,
+			RequeueAfter: time.Second * 12,
```
Comment (sbar95) [inline pkg/controller/gitopsconfig/controller.go]: **Why decrease?**
Before, when there's been a successful hello-world application deployment and then one decided to delete the gitopsconfig, one had to wait for one minute for the finalizer to be removed. Only then k8s garbage collector could remove the gitopsconfig.

Before:
<details><summary><code>time kubectl delete gitopsconfigs.eunomia.kohls.io --all -n eunomia-hello-world-yaml-demo</code></summary><br><pre>
$ time kubectl delete gitopsconfigs.eunomia.kohls.io --all -n eunomia-hello-world-yaml-demo 
gitopsconfig.eunomia.kohls.io "hello-world-yaml" deleted

real    1m0.731s
user    0m0.131s
sys     0m0.183s
</pre></details>

Now:
<details><summary><code>time kubectl delete gitopsconfigs.eunomia.kohls.io --all -n eunomia-hello-world-yaml-demo</code></summary><br><pre>
$ time kubectl delete gitopsconfigs.eunomia.kohls.io --all -n eunomia-hello-world-yaml-demo 
gitopsconfig.eunomia.kohls.io "hello-world-yaml" deleted

real    0m12.543s
user    0m0.112s
sys     0m0.121s
</pre></details>

**But why 12s exactly?**
Because the job becomes successful [no sooner than 10s](https://github.com/KohlsTechnology/eunomia/blob/master/pkg/controller/gitopsconfig/jobmonitor.go#L187) after being launched. I just had to provide a bit higher value here.
I could've provided 5s (for example) but the next reconciliation loop would see the job pending and again a reconciliation loop would be scheduled (this time in half a minute) so the whole deletion process would take 35s.

File: template-processors/base/bin/wrapper.sh [hunk 2]
```diff
@@ -17,9 +17,18 @@
...
+    source $HOME/envs.sh
+    /usr/local/bin/processParameters.sh
+    /usr/local/bin/processTemplates.sh
+    /usr/local/bin/resourceManager.sh
+    ;;
+  delete)
+    /usr/local/bin/discoverEnvironment.sh
+    /usr/local/bin/resourceManager.sh
+    ;;
+esac
```
Comment (sbar95) [inline template-processors/base/bin/wrapper.sh]: Before, when there's been an unsuccessful hello-world application deployment and then one decided to delete the gitopsconfig, the command didn't return (because deletion job was failing on gitClone.sh, processParameters.sh, or processTemplates.sh - the finalizer was never removed, so k8s garbage collector couldn't remove the gitopsconfig).

Before:
<details><summary><code>time kubectl delete gitopsconfigs.eunomia.kohls.io --all -n eunomia-hello-world-yaml-demo</code></summary><br><pre>
$ time kubectl delete gitopsconfigs.eunomia.kohls.io --all -n eunomia-hello-world-yaml-demo 
gitopsconfig.eunomia.kohls.io "hello-world-yaml" deleted
^C
real    9m48.133s
user    0m0.188s
sys     0m0.195s
</pre></details>

Now:
<details><summary><code>time kubectl delete gitopsconfigs.eunomia.kohls.io --all -n eunomia-hello-world-yaml-demo</code></summary><br><pre>
$ time kubectl delete gitopsconfigs.eunomia.kohls.io --all -n eunomia-hello-world-yaml-demo 
gitopsconfig.eunomia.kohls.io "hello-world-yaml" deleted

real    0m12.661s
user    0m0.107s
sys     0m0.117s
</pre></details>

File: pkg/controller/gitopsconfig/jobmonitor.go [hunk 3]
```diff
@@ -157,6 +158,10 @@ func (job *jobmonitor) watchjob(instanceName, instanceNamespace string) {
 		time.Sleep(10 * time.Second)
 		jobState, err := job.checkResult()
 		if err != nil {
+			if strings.Contains(err.Error(), "not found") {
+				log.Info("The job has been deleted")
+				break
```
Comment (sbar95) [inline pkg/controller/gitopsconfig/jobmonitor.go]: Before, when there's been a deployment, the job was being watched for status and in the meantime one decided to remove the namespace, the nonexistent job was being watched for status without an end.

Before:
<details><summary><code>Logs from eunomia-operator</code></summary><br><pre>
{"level":"error","ts":1576746595.449615,"logger":"controller_gitopsconfig","msg":"Error in GetJob for CheckResult","error":"Job.batch \"gitopsconfig-hello-world-yaml-nd2iir\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*jobmonitor).checkResult\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:191\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*jobmonitor).watchjob\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:158\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.watchJobForStatus\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:143"}
{"level":"info","ts":1576746615.454666,"logger":"controller_gitopsconfig","msg":"retrying the GetJob for CheckResult"}
{"level":"error","ts":1576746615.454728,"logger":"controller_gitopsconfig","msg":"Error in GetJob for CheckResult","error":"Job.batch \"gitopsconfig-hello-world-yaml-nd2iir\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*jobmonitor).checkResult\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:191\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*jobmonitor).watchjob\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:158\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.watchJobForStatus\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:143"}
{"level":"info","ts":1576746635.4603698,"logger":"controller_gitopsconfig","msg":"retrying the GetJob for CheckResult"}
{"level":"error","ts":1576746635.460654,"logger":"controller_gitopsconfig","msg":"Error in GetJob for CheckResult","error":"Job.batch \"gitopsconfig-hello-world-yaml-nd2iir\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*jobmonitor).checkResult\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:191\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*jobmonitor).watchjob\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:158\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.watchJobForStatus\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:143"}
{"level":"info","ts":1576746655.463279,"logger":"controller_gitopsconfig","msg":"retrying the GetJob for CheckResult"}
{"level":"error","ts":1576746655.463386,"logger":"controller_gitopsconfig","msg":"Error in GetJob for CheckResult","error":"Job.batch \"gitopsconfig-hello-world-yaml-nd2iir\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*jobmonitor).checkResult\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:191\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*jobmonitor).watchjob\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:158\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.watchJobForStatus\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:143"}
{"level":"info","ts":1576746675.481663,"logger":"controller_gitopsconfig","msg":"retrying the GetJob for CheckResult"}
{"level":"error","ts":1576746675.481712,"logger":"controller_gitopsconfig","msg":"Error in GetJob for CheckResult","error":"Job.batch \"gitopsconfig-hello-world-yaml-nd2iir\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*jobmonitor).checkResult\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:191\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*jobmonitor).watchjob\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:158\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.watchJobForStatus\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:143"}
{"level":"info","ts":1576746695.5009239,"logger":"controller_gitopsconfig","msg":"retrying the GetJob for CheckResult"}
{"level":"error","ts":1576746695.50108,"logger":"controller_gitopsconfig","msg":"Error in GetJob for CheckResult","error":"Job.batch \"gitopsconfig-hello-world-yaml-nd2iir\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*jobmonitor).checkResult\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:191\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*jobmonitor).watchjob\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:158\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.watchJobForStatus\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:143"}
{"level":"info","ts":1576746715.511931,"logger":"controller_gitopsconfig","msg":"retrying the GetJob for CheckResult"}
{"level":"error","ts":1576746715.512026,"logger":"controller_gitopsconfig","msg":"Error in GetJob for CheckResult","error":"Job.batch \"gitopsconfig-hello-world-yaml-nd2iir\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*jobmonitor).checkResult\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:191\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*jobmonitor).watchjob\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:158\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.watchJobForStatus\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:143"}
{"level":"info","ts":1576746735.515382,"logger":"controller_gitopsconfig","msg":"retrying the GetJob for CheckResult"}
{"level":"error","ts":1576746735.515475,"logger":"controller_gitopsconfig","msg":"Error in GetJob for CheckResult","error":"Job.batch \"gitopsconfig-hello-world-yaml-nd2iir\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*jobmonitor).checkResult\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:191\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.(*jobmonitor).watchjob\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:158\ngithub.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig.watchJobForStatus\n\t/Users/sbar/go/src/github.com/KohlsTechnology/eunomia/pkg/controller/gitopsconfig/jobmonitor.go:143"}
...
</pre></details>

Now:
<details><summary><code>Logs from eunomia-operator</code></summary><br><pre>
{"level":"info","ts":1576747151.492175,"logger":"controller_gitopsconfig","msg":"retrying the GetJob for CheckResult"}
{"level":"info","ts":1576747151.492248,"logger":"controller_gitopsconfig","msg":"Retry of GetJob for CheckResult unsuccessful: Job.batch \"gitopsconfig-hello-world-yaml-fjxaon\" not found"}
{"level":"info","ts":1576747151.492257,"logger":"controller_gitopsconfig","msg":"The job has been deleted"}
</pre></details>

File: pkg/controller/gitopsconfig/controller.go [hunk 4]
```diff
@@ -414,24 +414,23 @@ func (r *Reconciler) manageDeletion(instance *gitopsv1alpha1.GitOpsConfig) (reco
...
 		}, nil
 	}
 	//There should be only one pending job
 	job := applicableJobList[0]
-	if job.Status.Succeeded > 0 {
+	if job.Status.Succeeded > 0 || job.Status.Failed >= *job.Spec.BackoffLimit {
```
Comment (akavel) [inline pkg/controller/gitopsconfig/controller.go]: As we discussed, I'd be grateful if you could remove the finalizer cleanup in case Job has failed. I believe it's better (if uglier) to still hang (so that user knows there's something wrong), than to hide the failure under the rug (and leave the user oblivious to the fact stuff didn't get deleted).

File: pkg/controller/gitopsconfig/jobmonitor.go [hunk 5]
```diff
@@ -188,7 +193,7 @@ func (job *jobmonitor) checkResult() (jobState gitopsv1alpha1.GitOpsConfigStatus
 		log.Info("retrying the GetJob for CheckResult")
 		jobOutput, err = job.getjobmonitor()
 		if err != nil {
-			log.Error(err, "Error in GetJob for CheckResult")
```
Comment (akavel) [inline pkg/controller/gitopsconfig/jobmonitor.go]: Why change Error to Info?

File: pkg/controller/gitopsconfig/controller.go (hunk 1 above)
Comment (akavel) [reply pkg/controller/gitopsconfig/controller.go]: I don't understand the "no sooner than 10s" explanation. The line you link to in jobmonitor.go sets the Status field of GitOpsConfig. Whereas, AFAIU, manageDeletion checks Status field of a Job object. In what way does the jobmonitor.go link explain that the job becomes successful no sooner than 10s?

To be clear: personally, I'm all for shortening this time span (I find the 1m super annoying).

File: pkg/controller/gitopsconfig/jobmonitor.go (hunk 5 above)
Comment (sbar95) [reply pkg/controller/gitopsconfig/jobmonitor.go]: I don't find anything error-like in this case. I.e. for me this is a rather normal case which can happen and user should be notified of it with an information, not error

File: template-processors/base/bin/discoverEnvironment.sh [hunk 6]
```diff
@@ -22,7 +22,11 @@ function setContext {
 }
 
 function kube {
-  $kubectl -s https://kubernetes.default.svc:443  --token $(cat /var/run/secrets/kubernetes.io/serviceaccount/token) --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt $@
+  $kubectl \
+    -s https://kubernetes.default.svc:443 \
+    --token $(cat /var/run/secrets/kubernetes.io/serviceaccount/token) \
```
Comment (akavel) [inline template-processors/base/bin/discoverEnvironment.sh]: If you're changing this line already, please also fix it to wrap the `$()` in proper double quotes `"$( ... )"`

File: pkg/controller/gitopsconfig/controller.go [hunk 7]
```diff
@@ -427,11 +427,11 @@ func (r *Reconciler) manageDeletion(instance *gitopsv1alpha1.GitOpsConfig) (reco
 		}
 		return reconcile.Result{}, nil
 	}
-	//if it's not succeeded we wait for 1 minute
+	//if it's not succeeded we wait for half a minute
 	//TODO add logic to stop at a certain point ... or not ...
 	return reconcile.Result{
 		Requeue:      true,
-		RequeueAfter: time.Minute,
+		RequeueAfter: time.Second * 30,
```
Comment (akavel) [inline pkg/controller/gitopsconfig/controller.go]: As we discussed, I would suggest one time amount here and in l.417, and removing the reference to jobmonitor.go (here and in commit message), and adding a TODO comment about exponential backoff, maybe like in CronJob, if you believe it makes sense.

File: pkg/controller/gitopsconfig/controller.go (hunk 1 above)
Comment (sbar95) [reply pkg/controller/gitopsconfig/controller.go]: Right, I had some misconception about it - I set it to a fixed value of 5 seconds.

File: template-processors/base/bin/wrapper.sh [hunk 8]
```diff
@@ -17,9 +17,18 @@
...
+    /usr/local/bin/discoverEnvironment.sh
+    source $HOME/envs.sh
+    /usr/local/bin/processParameters.sh
+    /usr/local/bin/processTemplates.sh
+    /usr/local/bin/resourceManager.sh
+    ;;
+  delete)
+    /usr/local/bin/discoverEnvironment.sh
+    /usr/local/bin/resourceManager.sh
+    ;;
```
Comment (akavel) [inline template-processors/base/bin/wrapper.sh]: @seanmalloy: ***Important question:*** this PR seems to me to change the behavior for `kubectl delete GitOpsConfig` finalizer when CR has `ResourceHandlingMode: "Patch"`. Question is, was the old behavior in this case even correct? Or, maybe even better question: **What is our intended behavior in this case?** As far as I understand, after this PR, we would effectively do nothing in the finalizer in such case. Previous code seemed to me to try and *delete all the resources listed in the repo*, which is potentially dangerous in my opinion. Personally, I would think doing nothing is the safer choice here, and as such would be OK with this PR's behavior.

File: template-processors/base/bin/resourceManager.sh [hunk 9]
```diff
@@ -75,8 +66,13 @@ function deleteByOldLabels {
...
   fi
-  kube delete "$ownedKinds" \
-    -l "$TAG_OWNER==$owner,$TAG_APPLIED!=$timestamp"
+  if [[ -n "${timestamp-}" ]]; then
+    kube delete "$ownedKinds" \
+      -l "$TAG_OWNER==$owner,$TAG_APPLIED!=$timestamp"
+  else
+    kube delete "$ownedKinds" \
+      -l "$TAG_OWNER==$owner"
+  fi
```
[the remark this answers is not in the document]
Comment (sbar95) [reply template-processors/base/bin/resourceManager.sh]: This code is more compact, I'll borrow it

File: template-processors/base/bin/wrapper.sh (hunk 8 above)
Comment (seanmalloy) [reply template-processors/base/bin/wrapper.sh]: After some discussion the question is should be deleting resources that eunomia is only patching. :-)

Comment (seanmalloy) [reply template-processors/base/bin/wrapper.sh]: We will not delete resources that eunomia has only patched.
