### PR TITLE
Resource deletion mode bug

### LINKED ISSUE #311: Setting resourceDeletionMode to None Prevents Applying Resources
**What version of eunomia are you using?**

<details><summary><code>kubectl exec $EUNOMIA_POD curl localhost:8383/metrics</code> Output</summary><br><pre>
$ kubectl get -n eunomia-operator endpoints/eunomia-operator -o jsonpath='{.subsets[*].addresses[*].targetRef.name}' | xargs -I% kubectl exec -n eunomia-operator % -- curl -sS localhost:8383/metrics | grep eunomia_build_info

</pre></details>

eunomia version: v0.1.4

**Does this issue reproduce with the latest release?**
yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
OCP v3.11
</pre></details>

**What did you do?**
I created a GitOpsConfig with the `resourceDeletionMode` set to `None.
```
---
apiVersion: eunomia.kohls.io/v1alpha1
kind: GitOpsConfig
metadata:
  name: namespace-poc
spec:
  templateSource:
    uri: https://github.example.com/Operations/namespaces
    ref: master
    contextDir: foo/namespaces
    secretRef: eunomia-runner-github
  triggers:
  - type: Webhook
  serviceAccountRef: eunomia-runner
  templateProcessorImage: docker-registry.default.svc:5000/images/eunomia-base:latest
  resourceHandlingMode: Apply
  resourceDeletionMode: None
```

**What did you expect to see?**
I expected that new a modified resource should be applied using this GitOpsConfig.

**What did you see instead?**
The `kubectl apply` command is not run in the k8s `Job` created by Eunomia. The `Job` logs from the base template processor show the below message ...

```
+ echo 'Processing Parameters'
--
  | + FOLDERS=
  | Processing Parameters
  | + '[' -e /git/parameters/./hierarchy.lst ']'
  | + FOLDERS=/git/parameters/.
  | + '[' -n /git/parameters/. ']'
  | + VALUES_FILE=/tmp/eunomia_values_processed1.yaml
  | + echo ---
  | + for DIR in ${FOLDERS}
  | Processing files in /git/parameters/.
  | + echo 'Processing files in /git/parameters/.'
  | ++ find /git/parameters/. -maxdepth 1 -name '*.json' -o -name '*.yaml' -o -name '*.yml'
  | + YAML_FILES=/git/parameters/./cr.yaml
  | + '[' /git/parameters/./cr.yaml ']'
  | + goyq merge -i -x /tmp/eunomia_values_processed1.yaml /git/parameters/./cr.yaml
  | + '[' -e /tmp/eunomia_values_processed1.yaml ']'
  | + envsubst
  | + /usr/local/bin/processTemplates.sh
  | + echo Processing Templates
  | + cp -R /git/templates/foo/namespaces/. /git/manifests/
  | Processing Templates
  | + /usr/local/bin/resourceManager.sh
  | + TAG_OWNER=gitopsconfig.eunomia.kohls.io/owner
  | + TAG_APPLIED=gitopsconfig.eunomia.kohls.io/applied
  | + '[' Apply == None ']'
  | + '[' None == None ']'
  | + echo 'CREATE_MODE and/or DELETE_MODE is set to None; This means that the template processor already applied the resources. Skipping the Manage Resources step.'
  | + exit 0
  | CREATE_MODE and/or DELETE_MODE is set to None; This means that the template processor already applied the resources. Skipping the Manage Resources step.
```

### PR DESCRIPTION
**Pull request by jimmyfigiel**
**Description**

template-proccessors/resourceManager: eliminate dependency between CREATE_MODE and DELETE_MODE

This change eliminate dependency between CREATE_MODE=None and DELETE_MODE=None
which enables creates and deletes to run independently of each other.  Prior to
this setting DELETE_MODE to none would prevent any resources from being set
And vice versa.

Fixes #311

**Type of change**

* Bug fix (non-breaking change which fixes an issue)

**Checklist**

- [X] Unit tests and e2e tests updated
- [ ] Documentation updated

### CODE REVIEW

File: template-processors/base/bin/resourceManager.sh [hunk 1]
```diff
@@ -110,14 +115,9 @@ function createUpdateResources() {
...
 
-if [ "$CREATE_MODE" == "None" ] || [ "$DELETE_MODE" == "None" ]; then
-    echo "CREATE_MODE and/or DELETE_MODE is set to None; This means that the template processor already applied the resources. Skipping the Manage Resources step."
-    exit 0
-fi
-
 echo "Managing Resources"
 setContext
-# NOTE: Kubernetes currently requires that first *and last* character of
+# NOTE: Kubernetes currently requires that first *and last* character of
```
Comment (Smiley73) [inline template-processors/base/bin/resourceManager.sh:120]: Remove the whitespace that was added at the end of the line.

File: template-processors/base/bin/resourceManager.sh [hunk 2]
```diff
@@ -110,14 +115,9 @@ function createUpdateResources() {
     esac
```
Comment (Smiley73) [inline template-processors/base/bin/resourceManager.sh:115]: Would it make sense to add `None` to the `case` statement, so that's it's clear what's happening when this mode is set?

Comment (Smiley73) [reply template-processors/base/bin/resourceManager.sh:115]:
```suggestion
    None)
        ;;
    esac
```

**Comment by Smiley73** [comment]
@jimmyfigiel this is looking good. Now the only thing we're missing is a test case for this.

File: template-processors/base/bin/resourceManager.sh [hunk 3]
```diff
@@ -107,14 +112,10 @@ function createUpdateResources() {
     Replace)
         kube replace -R -f "$MANIFEST_DIR"
         ;;
+    None) ;;
```
[the remark this answers is not in the document]
Comment (jimmyfigiel) [reply template-processors/base/bin/resourceManager.sh:115]: It's always going to call the function "createUpdateResources" so there is really no message to print here.  I removed the initial check which was the original problem.  The case statement prevent creation as it should, vs needing a message for an error.

**Comment by seanmalloy** [comment]
@jimmyfigiel thanks for for your contribution!
