### PR TITLE
Make proxy in eunomia-base work

### LINKED ISSUE #154: Setting proxy in eunomia-base doesn't work for git
**What version of eunomia are you using?**

eunomia version: v0.0.3

**Does this issue reproduce with the latest release?**

yes

**What operating system and processor architecture are you using (`kubectl version`)?**

n/a

**What did you do?**

In my environment I need to use proxy. I set such GitOpsConfig:
```
apiVersion: eunomia.kohls.io/v1alpha1
kind: GitOpsConfig
metadata:
  name: hello-world-yaml
spec:
  templateSource:
    uri: https://github.com/KohlsTechnology/eunomia
    ref: master
    contextDir: examples/hello-world-yaml/template1
    httpProxy: http://my-proxy.com:my-port
    httpsProxy: http://my-proxy.com:my-port
  parameterSource:
    ref: master
    contextDir: examples/hello-world-yaml/parameters
    httpProxy: http://my-proxy.com:my-port
    httpsProxy: http://my-proxy.com:my-port
  triggers:
  - type: Change
  #- type: Periodic
    #cron: '*/1 * * * *'
  serviceAccountRef: eunomia-runner-yaml
  templateProcessorImage: docker-registry.default.svc:5000/my-namespace/eunomia-base:latest
  resourceHandlingMode: CreateOrMerge
  resourceDeletionMode: Delete
```
I create a proper namespace and service account. Then I apply the above GitOpsConfig.

**What did you expect to see?**

image

**What did you see instead?**

image

**Solution**

This line
https://github.com/KohlsTechnology/eunomia/blob/master/template-processors/base/bin/gitClone.sh#L47
should be
`git clone -c "http.proxy=$TEMPLATE_GIT_HTTP_PROXY" -b $TEMPLATE_GIT_REF $TEMPLATE_GIT_URI $TEMPLATE_GIT_DIR`

And this line
https://github.com/KohlsTechnology/eunomia/blob/master/template-processors/base/bin/gitClone.sh#L77
should be
`git clone -c "http.proxy=$PARAMETER_GIT_HTTP_PROXY" -b $PARAMETER_GIT_REF $PARAMETER_GIT_URI $PARAMETER_GIT_DIR`

### PR DESCRIPTION
**Pull request by sbar95**
Export http_proxy, https_proxy, and no_proxy for them to have effect
on git (they must be env variables in order to work).

Make the variables local to functions and export them in subshells in
order not to affect the whole script scope - envs from function
pullFromTemplatesRepo don't affect those from function
pullFromParametersRepo and vice versa.

**Description**

Fixes #154 

**Type of change**

* Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: template-processors/base/bin/gitClone.sh [hunk 1]
```diff
@@ -21,15 +21,15 @@ function pullFromTemplatesRepo {
   set +u
   if [ ! -z "$TEMPLATE_GIT_HTTP_PROXY" ] 
   then
-    http_proxy=$TEMPLATE_GIT_HTTP_PROXY
+    local http_proxy=$TEMPLATE_GIT_HTTP_PROXY
```
Comment (akavel) [inline template-processors/base/bin/gitClone.sh]: Cool! Just, why the `local` and the subshell below, instead of just doing `export` here?

Comment (akavel) [reply template-processors/base/bin/gitClone.sh]: argh, I see explanation in the commit message, sorry! :)

File: template-processors/base/bin/gitClone.sh [hunk 2]
```diff
@@ -44,22 +44,27 @@ function pullFromTemplatesRepo {
   fi 
   set -u
   mkdir -p $TEMPLATE_GIT_DIR
-  git clone -b $TEMPLATE_GIT_REF $TEMPLATE_GIT_URI $TEMPLATE_GIT_DIR
+  (
+    export http_proxy
+    export https_proxy
+    export no_proxy
+    git clone -b $TEMPLATE_GIT_REF $TEMPLATE_GIT_URI $TEMPLATE_GIT_DIR
```
Comment (akavel) [inline template-processors/base/bin/gitClone.sh]: Cool with me! :) Just please put each variable in double quotes `"`
