### PR TITLE
unit test for race condition fix

### LINKED ISSUE #179: Race condition between jobs started by eunomia
**What version of eunomia are you using?**

eunomia version: 0.0.4

**Does this issue reproduce with the latest release?**

yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

As noticed by @safirh, there is race condition between jobs started by eunomia. Specifically, if two reconciliation requests for a CR (say, "A" and "B") are submitted after each other (esp. when the time between them is short; for example, as a result of two Webhook triggers from two commits), eunomia would *start* a new Job for the 2nd version of the CR (B) *before the Job for the 1st one (A) ended*. The two jobs would then be running concurrently, and with nondeterministic scheduling in Kubernetes, it can happen that the Job B will end (run resourceManager.sh) *before* Job A. As a result, Job A's "apply" would then override Job B's "apply", leaving cluster in old state.

This gets even more problematic when we implement a "status" field for the CRD in eunomia, as adding job info and git SHA1 info there would be confusing and misleading, with races between jobs running in parallel.

**What did you expect to see?**

I would expect that new job, for applying a newer version of a CR, would be postponed until the previous job (for an older version of the CR) finished (with success or failure).

**What did you see instead?**

Jobs for two versions of a CR from the same Git repository may run concurrently, leading to a race condition, where the result of applying the older version/commit of the CR may override the result of applying the newer version/commit of the CR.

### PR DESCRIPTION
**Pull request by safirh**
**Description**

Unit tests for race condition fix [PR](https://github.com/KohlsTechnology/eunomia/pull/237)

Fixes #179 

**Type of change**

* Bug fix (non-breaking change which fixes an issue)
**Checklist**

- [x] Unit tests and e2e tests updated
- [ ] Documentation updated

### CODE REVIEW

File: pkg/controller/gitopsconfig/controller.go [hunk 1]
```diff
@@ -235,7 +235,7 @@ func (r *Reconciler) createJob(jobtype string, instance *gitopsv1alpha1.GitOpsCo
 		return reconcile.Result{}, xerrors.Errorf("unable to list the jobs in namespace %q: %w", instance.Namespace, err)
 	}
 	for _, j := range jobList.Items {
-		if isOwner(instance, &j) && j.Status.Active != 0 {
+		if isOwner(instance, &j) && (j.Status.Active != 0 || j.Status.StartTime.IsZero()) && instance.DeletionTimestamp.IsZero() {
```
Comment (akavel) [inline pkg/controller/gitopsconfig/controller.go]: Based on our talk on chat, I now understand that the check of `DeletionTimestamp.IsZero` is a workaround to make TestCreatingDeleteJob pass, and I believe I understand more about the context why you did it this way. Thanks to your explanations, I also now finally understood the meaning of the idea you said before, that I didn't understand at that time — to modify Job.Status in the "fake client" used in TestCreatingDeleteJob. Based on this, I believe this idea you had was the correct solution here, so I would like to ask you to change it now, to:

 1. remove the `IsZero` check from this line
 2. in TestCreatingDeleteJob, add code that will simulate a change of the action=create Job Status to "completed", to allow Reconcile to make a new action=delete job

File: pkg/controller/gitopsconfig/controller_test.go [hunk 2]
```diff
@@ -562,3 +564,66 @@ func findDeleteJob(cl client.Client) batch.Job {
...
+	req := reconcile.Request{
+		NamespacedName: nsn,
+	}
+
+	numberOfJobs := 2
+	var wg sync.WaitGroup
+	for i := 1; i <= numberOfJobs; i++ {
+		wg.Add(1)
+		// in order to replicate reconciler being called for creating an another job.
+		go func() {
```
Comment (akavel) [inline pkg/controller/gitopsconfig/controller_test.go]: Instead of running goroutines, can we just call Reconcile two times, one after another? or are there reasons why we cannot or should not do this?

File: pkg/controller/gitopsconfig/controller_test.go [hunk 3]
```diff
@@ -562,3 +564,66 @@ func findDeleteJob(cl client.Client) batch.Job {
...
+			r.Reconcile(req)
```
Comment (akavel) [inline pkg/controller/gitopsconfig/controller_test.go]: Instead of running Reconcile, could we just call `r.createJob`? or are there reasons why we cannot or should not do this?

File: pkg/controller/gitopsconfig/controller_test.go [hunk 4]
```diff
@@ -562,3 +564,66 @@ func findDeleteJob(cl client.Client) batch.Job {
...
+			wg.Done()
+		}()
+		time.Sleep(3 * time.Second)
```
Comment (akavel) [inline pkg/controller/gitopsconfig/controller_test.go]: Why we need to run Sleep here? In general, it is much better if all tests can be made to run as quickly as possible, to avoid wasting everybody's time; adding Sleep makes tests run much longer, so it is usually better if tests can be modified in some way to still work correctly, but not using Sleep or other time delays, or at least to make them as short as possible if they are absolutely necessary

File: pkg/controller/gitopsconfig/controller_test.go [hunk 5]
```diff
@@ -562,3 +564,66 @@ func findDeleteJob(cl client.Client) batch.Job {
...
+	}
+	wg.Wait()
+
+	job, _ := findJobList(cl)
```
Comment (akavel) [inline pkg/controller/gitopsconfig/controller_test.go]: please don't ignore errors from functions, but instead, make sure test fails when there is error from function, for example:

```
if err != nil {
    t.Error(err)
}
```

File: pkg/controller/gitopsconfig/controller_test.go [hunk 6]
```diff
@@ -453,6 +451,19 @@ func TestCreatingDeleteJob(t *testing.T) {
 		log.Error(err, "Update CRD", "Failed Updating CRD type of GitOpsConfig")
 	}
 
+	// fakeclient is not updating the job status , inorder to create the job with different action
+	//updating the job status manually
```
Comment (akavel) [inline pkg/controller/gitopsconfig/controller_test.go]: Please also add information here explaining that this job we are updating exists because it was created by  Reconcile.

File: pkg/controller/gitopsconfig/controller_test.go (hunk 5 above)
Comment (safirh) [reply pkg/controller/gitopsconfig/controller_test.go]: Changes done

File: pkg/controller/gitopsconfig/controller_test.go (hunk 4 above)
Comment (safirh) [reply pkg/controller/gitopsconfig/controller_test.go]: Changes done

File: pkg/controller/gitopsconfig/controller_test.go (hunk 3 above)
Comment (safirh) [reply pkg/controller/gitopsconfig/controller_test.go]: I followed this pattern as we have used reconcile in all other test cases as a standard rather than using a createJob.

File: pkg/controller/gitopsconfig/controller_test.go (hunk 2 above)
Comment (safirh) [reply pkg/controller/gitopsconfig/controller_test.go]: changes done

File: pkg/controller/gitopsconfig/controller.go (hunk 1 above)
Comment (safirh) [reply pkg/controller/gitopsconfig/controller.go]: Changes done

File: pkg/controller/gitopsconfig/controller_test.go [hunk 7]
```diff
@@ -595,21 +606,28 @@ func TestCreateJob(t *testing.T) {
...
-	job, _ := findJobList(cl)
+	err := cl.Update(context.TODO(), &job)
+	if err != nil {
+		log.Error(err, "Update job", "Failed to Updating the job status")
+	}
+	r.Reconcile(req)
+	jobCount, err := findJobList(cl)
 
-	if job == numberOfJobs {
+	if err != nil {
```
Comment (akavel) [inline pkg/controller/gitopsconfig/controller_test.go]: Please remove empty line above this check; in Go it is best style when `if err != nil {` check line is as close as possible to the line where the `err` it is checking was set - this is a very important check, and keeping it as close as possible makes it easiest to immediately see that it was not forgotten.

File: pkg/controller/gitopsconfig/controller_test.go [hunk 8]
```diff
@@ -595,21 +606,28 @@ func TestCreateJob(t *testing.T) {
...
+		log.Error(err, "Job list", "Failed to fetch job list")
+	}
+	if jobCount == numberOfJobs {
```
Comment (akavel) [inline pkg/controller/gitopsconfig/controller_test.go]: I believe it would be better to remove `numberOfJobs` variable, and just check here `if jobCount > 1`. If I understand correctly, in this test we want to verify that no new jobs were created, regardless of exact number - too many jobs (more than 2) would be also incorrect.

File: pkg/controller/gitopsconfig/controller_test.go [hunk 9]
```diff
@@ -627,3 +645,21 @@ func findJobList(cl client.Client) (int, error) {
...
+	jobList := &batchv1.JobList{}
+	// Looking up all jobs
+	err := cl.List(context.TODO(), &client.ListOptions{
+		Namespace: namespace,
+	}, jobList)
+	if err != nil {
+		log.Error(err, "unable to list jobs")
+		return batch.Job{}
+	}
+	// Return the first instance that is a delete job
```
Comment (akavel) [inline pkg/controller/gitopsconfig/controller_test.go]: This comment says about a delete job, are you sure this is correct?

File: pkg/controller/gitopsconfig/controller_test.go [hunk 10]
```diff
@@ -562,3 +575,91 @@ func findDeleteJob(cl client.Client) batch.Job {
...
+	for _, job := range jobList.Items {
+		return job
+	}
```
Comment (akavel) [inline pkg/controller/gitopsconfig/controller_test.go]: please change above block to:

```
if len(jobList.Items) > 0 {
    return jobList.Items[0]
}
```

Using `for` here is technically correct, but using `if` better conveys the idea that we want to return at most 1 result; using `for` suggests we want to do something more than once with elements of jobList.Items, which makes it misleading.

Comment (safirh) [reply pkg/controller/gitopsconfig/controller_test.go]: changes done

File: pkg/controller/gitopsconfig/controller_test.go (hunk 9 above)
Comment (safirh) [reply pkg/controller/gitopsconfig/controller_test.go]: fixed the comment

File: pkg/controller/gitopsconfig/controller_test.go (hunk 8 above)
Comment (safirh) [reply pkg/controller/gitopsconfig/controller_test.go]: changes done

File: pkg/controller/gitopsconfig/controller_test.go (hunk 7 above)
Comment (safirh) [reply pkg/controller/gitopsconfig/controller_test.go]: removed empty line

File: pkg/controller/gitopsconfig/controller_test.go (hunk 6 above)
Comment (safirh) [reply pkg/controller/gitopsconfig/controller_test.go]: changes done

File: pkg/controller/gitopsconfig/controller.go [hunk 11]
```diff
@@ -235,7 +235,7 @@ func (r *Reconciler) createJob(jobtype string, instance *gitopsv1alpha1.GitOpsCo
 		return reconcile.Result{}, xerrors.Errorf("unable to list the jobs in namespace %q: %w", instance.Namespace, err)
 	}
 	for _, j := range jobList.Items {
-		if isOwner(instance, &j) && (j.Status.Active != 0 || j.Status.StartTime.IsZero()) && instance.DeletionTimestamp.IsZero() {
+		if isOwner(instance, &j) && j.Status.Active != 0 {
```
[the remark this answers is not in the document]
Comment (safirh) [reply pkg/controller/gitopsconfig/controller.go]: reverted back

File: pkg/controller/gitopsconfig/controller_test.go [hunk 12]
```diff
@@ -451,8 +451,8 @@ func TestCreatingDeleteJob(t *testing.T) {
 		log.Error(err, "Update CRD", "Failed Updating CRD type of GitOpsConfig")
 	}
 
-	// fakeclient is not updating the job status , inorder to create the job with different action
-	//updating the job status manually
+    // fakeclient is not updating the job status , inorder to create the new job we are
```
Comment (akavel) [inline pkg/controller/gitopsconfig/controller_test.go]: fix gofmt to fix Travis fail

Comment (safirh) [reply pkg/controller/gitopsconfig/controller_test.go]: gofmt fixed
