### PR TITLE
pkg/controller/gitopsconfig: delete stuck jobs when finalizing

### LINKED ISSUE #216: kubectl delete gitopsconfig command hangs when templateProcessorImage wrong in CR
**What version of eunomia are you using?**

eunomia version: v0.0.5

**Does this issue reproduce with the latest release?**

yes

**What operating system and processor architecture are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e851274
9", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:34Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14
b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
</pre></details>

**What did you do?**

I issued first three commands from [hello-world-yaml example app](https://github.com/KohlsTechnology/eunomia/blob/master/examples/hello-world-yaml/README.md#example) but with a wrong (nonexistent/unreachable) [templateProcessorImage](https://github.com/KohlsTechnology/eunomia/blob/master/examples/hello-world-yaml/cr/hello-world-cr1.yaml#L18).

Then, after some time I decided to delete the gitopsconfig.

**What did you expect to see?**

Deleted gitopsconfig.

**What did you see instead?**

`kubectl delete gitopsconfig/hello-world-yaml -n eunomia-hello-world-yaml-demo` command freezes.

**Information**

This issue derives from #52 but contrary to other cases described there this one is nontrivial so I create this story to track it separately.

### PR DESCRIPTION
**Pull request by akavel**
**Description**

In GitOpsConfig finalizer, find and delete any stuck Jobs.

Previously, if GitOpsConfig had a bad template processor image path, its
Job would never complete, stuck in a "Waiting" phase, with an error
message. When deleting a GitOpsConfig, the finalizer would then try to
create another Job, which would also get stuck, making it impossible to
complete deletion of GitOpsConfig.

This PR changes the algorithm of GitOpsConfig finalizer to
enable handling one more special case, when a Job is stuck with one of
known error messages. In such case, finalizer now deletes the Job (with
its corresponding Pods), and doesn't create a new finalizer Job.

Fixes #216.

**Type of change**

* Bug fix (non-breaking change which fixes an issue)

**Checklist**

- [x] Unit tests and e2e tests updated
- [ ] ~~Documentation updated~~  N/A

### CODE REVIEW

File: pkg/controller/gitopsconfig/controller.go [hunk 1]
```diff
@@ -389,79 +392,110 @@ func (r *Reconciler) manageDeletion(instance *gitopsv1alpha1.GitOpsConfig) (reco
...
+		log.Error(err, "GitOpsConfig finalizer unable to lookup instance's namespace", "instance", instance.Name)
+		return reconcile.Result{}, xerrors.Errorf("GitOpsConfig finalizer unable to lookup instance's namespace for %q: %w", instance.Name, err)
 	}
-	// looking up all delete jobs
-	err = r.client.List(context.TODO(), &client.ListOptions{
-		Namespace:     instance.GetNamespace(),
-		LabelSelector: selector,
-	}, jobList)
+	if !ns.DeletionTimestamp.IsZero() {
+		//namespace is being deleted
```
Comment (karolkrawczyk) [inline pkg/controller/gitopsconfig/controller.go]: Out of curiosity, in most comments there is space after `//`. Is there any specific reason why in few places it's missing? I'll also mark other code lines.

File: pkg/controller/gitopsconfig/controller.go [hunk 2]
```diff
@@ -389,79 +392,110 @@ func (r *Reconciler) manageDeletion(instance *gitopsv1alpha1.GitOpsConfig) (reco
...
+		if len(deleters) > 1 {
+			log.Error(nil, "too many delete jobs found (expected 1)", "n", len(deleters), "instance", instance.Name)
+			// TODO: should we return here, or try to still do something sensible for user?
 		}
-		return reconcile.Result{}, nil
+		done := deleters[0].Status.Succeeded > 0
+		if !done {
+			//if it's not succeeded we wait for 5 seconds
+			//TODO add logic to stop at a certain point ... or not ...
+			//TODO add exponential backoff, possibly like in CronJob
```
Comment (karolkrawczyk) [inline pkg/controller/gitopsconfig/controller.go]: Out of curiosity, in most comments there is space after `//`. Is there any specific reason why in few places it's missing? I'll also mark other code lines.

File: build/job-templates/cronjob.yaml [hunk 3]
```diff
@@ -6,6 +6,9 @@ metadata:
 spec:
   schedule: "{{ getCron .Config }}"
   jobTemplate:
+    metadata:
+      labels:
+        "gitopsconfig.eunomia.kohls.io/jobOwner": "{{ .Config.ObjectMeta.Name }}"
```
[the remark this answers is not in the document]
Comment (akavel) [reply build/job-templates/cronjob.yaml]: Wasn't sure, but it seems they're not needed indeed, thanks!

File: pkg/controller/gitopsconfig/controller.go [hunk 4]
```diff
@@ -389,79 +392,110 @@ func (r *Reconciler) manageDeletion(instance *gitopsv1alpha1.GitOpsConfig) (reco
 	if !containsString(instance.ObjectMeta.Finalizers, tagFinalizer) {
 		return reconcile.Result{}, nil
 	}
-	// we need to lookup the delete job and if it doesn't exist we launch it, then we see if it is completed successfully if yes we remove the finalizers, if no we return.
-	jobList := &batchv1.JobList{}
-	selector, err := labels.Parse("action=delete")
+
+	// To avoid a deadlock situation let's check if the namespace in which we are is maybe being deleted?
```
[the remark this answers is not in the document]
Comment (akavel) [reply pkg/controller/gitopsconfig/controller.go]: I meant this as part of the sentence, but if it's confusing, then I'll be removing it, thanks!

File: pkg/controller/gitopsconfig/controller.go (hunk 1 above)
Comment (akavel) [reply pkg/controller/gitopsconfig/controller.go]: They're moved verbatim from fragments of old code, so I wasn't sure whether to change them or not; but maybe it makes sense to improve them in process indeed, thanks!

File: pkg/controller/gitopsconfig/controller.go [hunk 5]
```diff
@@ -389,79 +392,111 @@ func (r *Reconciler) manageDeletion(instance *gitopsv1alpha1.GitOpsConfig) (reco
...
+		if xerrors.As(err, &errAPI) && errAPI.Status().Reason == metav1.StatusReasonConflict {
+			log.Error(err, "GitOpsConfig finalizer unable to remove itself; will retry", "instance", instance.Name)
+			return reconcile.Result{
+				RequeueAfter: 5 * time.Second,
+			}, xerrors.Errorf("GitOpsConfig finalizer unable to remove itself from %q, will retry: %w", instance.Name, err)
+		}
+		log.Error(err, "GitOpsConfig finalizer unable to remove itself", "instance", instance.Name)
+		return reconcile.Result{}, xerrors.Errorf("GitOpsConfig finalizer unable to remove itself from %q: %w", instance.Name, err)
+	}
+	return reconcile.Result{}, nil
```
Comment (karolkrawczyk) [inline pkg/controller/gitopsconfig/controller.go]: [optional] Do we want to log that finalizer was successfully deleted?

Comment (akavel) [reply pkg/controller/gitopsconfig/controller.go]: Good idea, thanks!
