### PR TITLE
Fix hardcoded v0.0.1 & "latest" tags

### LINKED ISSUE #64: Cleanup hardcoded v0.0.1 values in repo
In the Makefile, the version is hard-coded within the LDFLAGS
The template processor images are also hardcoded to build on top of the `v0.0.1` base image.

## What happens?
* `github.com/KohlsTechnology/eunomia/version.Version` is always set to `v0.0.1`
* The template processor images always build on top of the `v0.0.1` image

## What were you expecting to happen?
* `github.com/KohlsTechnology/eunomia/version.Version` is set dynamically 
* The template processor image builds on top of the correct version image
* Correct container image tags are pushed to quay.io when GitHub release is created

### PR DESCRIPTION
**Pull request by akavel**
## Description

Fix hardcoded `v0.0.1` and `latest` tags in various places:
- github.com/KohlsTechnology/eunomia/version.Version
- docker image tags on quay.io

As a result of the fix, the tagging policy on quay.io is changed as follows:
- "latest" tag — will be always pointing to the newest official release [Note: this fix will get applied only starting from the next vX.Y.Z release]
- "dev" tag — will be pointing to an image built from the most recently pushed commit in the GitHub repository.

Fixes #64

## Type of change

* Bug fix (non-breaking change which fixes an issue)
* This change requires a documentation update

### CODE REVIEW

**Comment by akavel** [comment]
Build issues fixed. PTAL.

**Comment by akavel** [comment]
@vinny-sabatini Thanks!

@seanmalloy Would you like to merge this PR?

File: scripts/build/get-version.sh [hunk 1]
```diff
@@ -0,0 +1,10 @@
+#!/usr/bin/env bash
+
```
Comment (seanmalloy) [inline scripts/build/get-version.sh]: Please add `set -e` here, so that script will exit if any command fails.

Comment (akavel) [reply scripts/build/get-version.sh]: Done. PTAL
